### ISSUE TITLE
Update use of Python to default to and/or use Python 3

### ISSUE THREAD

**Issue by elextr** [geany/geany#2615]
Since distros are now not defining `python` and python 2 is dead, should be changed to `python3`, see also discussion on #2223

Goals:

- [x] Change from `python` to `python3` in the [`filedefs.python` file](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/data/filedefs/filetypes.python#L75) (see discussion in #2223).
- [x] Make the [`main.py` template](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/data/templates/files/main.py#L1) use `python3`. https://github.com/geany/geany/pull/3485
- [x] Switch [build system](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/m4/geany-gtkdoc-header.m4#L24) to use >= 3.x. #2903
- [x] Use Python3 for [Docutils](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/.travis.yml#L22) (ex. `python3-docutils` on Debians).
- [x] Update the [`create_py_tags.py` script](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/scripts/create_py_tags.py#L1) to use Python 3 (#2630 and #3039).
- [x] Update the [`gen-api-gtkdoc.py` script](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/scripts/gen-api-gtkdoc.py#L1) to use Python 3. https://github.com/geany/geany/pull/2903
- [x] Update the [`create_php_tags.py` script](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/scripts/create_php_tags.py#L1) to use Python 3. #3488
- [x] Update (or remove, does anybody use it? I wrote it and barely used it.) the [`rstrip-whitespace.py` script](https://github.com/geany/geany/blob/master/scripts/rstrip-whitespace.py) to use Python 3. #3486
- [x] Update the [`update-python-identifiers.sh` script](https://github.com/geany/geany/blob/master/scripts/update-python-identifiers.sh) to use only Python 3 (#2924).
- [x] OSX: Update [`plist_filetypes.py`](https://github.com/geany/geany-osx/blob/master/utils/plist_filetypes.py) to use Python 3. (Done in https://github.com/geany/geany-osx/commit/19bcb0a43d163eab05bbccbd96b141f101f391a4)

**Comment by elextr** [comment]
First noticed by @codebrainz not me.

**Comment by codebrainz** [comment]
I propose we expand this issue to become an omnibus tracker issue that includes:

- [ ] Change from `python` to `python3` in the [`filedefs.python` file](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/data/filedefs/filetypes.python#L75) (see discussion in #2223).
- [ ] Switch [build system](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/m4/geany-gtkdoc-header.m4#L24) to use >= 3.x.
- [ ] Use Python3 for [Docutils](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/.travis.yml#L22) (ex. `python3-docutils` on Debians).
- [ ] Update the [`create_py_tags.py` script](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/scripts/create_py_tags.py#L1) to use Python 3.
- [ ] Update the [`gen-api-gtkdoc.py` script](https://github.com/geany/geany/blob/397b24d6da711f32836a564928c4bb8004d438eb/scripts/gen-api-gtkdoc.py#L1) to use Python 3.

**Comment by elextr** [comment]
Sounds like a good idea, maybe best to change the issue title and move that to a checkpoint in the list.

Didn't know Geany had such a snake pit (a lot of pythons, dad joke).

**Comment by codebrainz** [comment]
> maybe best to change the issue title and move that to a checkpoint in the list.

Done, and tagged. I might have a crack at these mostly trivial changes, will ping here if I do.

**Comment by eht16** [comment]
Not even three later, we finally managed to finish all open tasks. Python 2 R.I.P.

**Comment by elextr** [comment]
Well, mainly you managed to do it so thanks.
