### ISSUE TITLE
Improving support of various languages

### ISSUE THREAD

**Issue by techee** [geany/geany#3651]
I went through the various open PRs and open issues providing/requesting support of certain languages because some seem to be a bit neglected:
- [x] There's #3171 adding Prolog support.
- [x] There's the Raku language support in #3169 which is hopefully in a mergable state.
- [ ] I created #3647 (Scintilla lexer for JSON) and #3648 (Scintilla lexer for Nim) - for JSON there has already been a pull request in the past and they have also been requested in some open issues and in general I agree that when there's a Scintilla lexer, we should use it.
- [x] Yesterday I reviewed #3480 (CIL language support) and if the minor comments I had get addresses, I think it should be merged.
- [ ] There are various open PRs and issues asking for Dart, LESS, and SCSS - these could be added as external filetypes. There should be no problem using C lexer for Dart and CSS lexer for LESS/SCSS (the CSS lexer supports LESS/SCSS modes).

What do you think?

**Comment by elextr** [comment]
Rereading the discussions of the PRs listed what has become obvious is that with only a few exceptions (@rdipardo thank you) most users of non-C languages are not going to contribute to, or test, unreleased filetypes.  So the only way of finding out how well filetype PRs work is to merge and release the filetype.  Then at least they might get feedback.  There should not be any impact on other users, a few kB code and some tiny filetypes files.

The biggest difficulty is going to be the size of the filetype menu :-)

I won't have access to my development machine for at least another week, but after then hopefully I can built all the PRs above and plug in random example files form the internet to see they work (not knowing any of those languages in detail).

**Comment by elextr** [comment]
On the filetypes menu.  

I have ranted before (at _least_ once) about the inadequacy of the current categories, so I won't go into it again. But really what is the difference between a scripting language and a programming language?  Why do we categorise Python as a scripting language when "Python is a programming language..." is the first text on its web page, or Ruby "A dynamic, open source programming language..." according to its web page.  But I guess Geany knows better than the language developers? And why are specialised languages like GLSL and VHDL occupying space in "Programming Languages" instead?  And its not about AOT compile [(see the table)](https://github.com/geany/geany/blob/7fd2507e6054617354fe941f2964be68b4536f44/src/filetypes.c#L127), Java is Jit not compiled, Julia is JIT or AOT compiled, but one is seen as a programming language and the other as a script, and languages like Python have more than one implementation, since Python has pypy and its a JIT, Python should be in programming languages with Java and so should Julia, and Ruby has Jruby that runs on the JVM, just like Java.  The categories don't make sense.

... Oops I seem to have ranted again, oh well while I'm in the mood let me go on to the issue of translations ... 

Why are just five of the more than 70 filetypes translated?  Specifically why are __these__ five translated, shell, makefile, CSS, conf, and PO?  

If a user is capable of writing a makefile surely they can understand "Make" and don't need "Makefile" translated, that seems condescending to me.  Same for "Sh" and "Shell", every current shell has "sh" in it, if a user is competent to write it they will understand what "Sh" is, and many languages don't bother to translate "Shell" (eg French, doesn't say Coquille, or German, Hülse? and those are the references for translations ;-).  And "CSS" and "Cascading Stylesheet", FGS!! if someone can read CSS they surely know what "CSS" means.  And "PO" and "Gettext translation", users don't write those files (they do edit them, but tools generate them) so the menu item is likely unused, so why go to the effort of translating it (and a quick look at some of the translations they leave "gettext" and just translate "translation", so why not just call the filetype "Gettext".

[end rant, I feel much better now]

If Geany dropped these frankly useless translations the filetypes menu could then be divided alphabetically, and could then grow in a more sustainable manner, if one sub menu gets too long move a few at the front or end to the previous or next submenu, and if two adjacent get too long split them into a new submenu in between.  Makes it simple.

**Comment by techee** [comment]
From my point of view this is pretty much completed. Using the JSON lexer from #3647 is a possibility but using the javascript lexer works well as well.
